export const CREATE_CONTACT = "CREATE_CONTACT";
export const LOAD_CONTACTS_SUCCESS = "LOAD_CONTACTS_SUCCESS";
export const LOAD_CREATORS_SUCCESS = "LOAD_CREATORS_SUCCESS";
export const CREATE_CONTACT_SUCCESS = "CREATE_CONTACT_SUCCESS";
export const UPDATE_CONTACT_SUCCESS = "UPDATE_CONTACT_SUCCESS";
export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";
export const DELETE_CONTACT_OPTIMISTIC = "DELETE_CONTACT_OPTIMISTIC";
